### PR TITLE
Adopt to merge of the servers

### PR DESCRIPTION
**Pull request by tkrille**
See osiam/osiam#43, osiam/osiam#44

### CODE REVIEW

**Comment by dacrome** [comment]
Thanks! Can you please change all links in the [docs](https://github.com/osiam/addon-self-administration/tree/master/docs) to the OSIAM server which is actually not used anymore and link instead to [osiam/osiam](https://github.com/osiam/osiam)? I grepped and found round about 20 relevant occurrences...

**Comment by dacrome** [comment]
I'm totally fine with the rest of your changes.

**Comment by tkrille** [comment]
I will, but I have to change the docs in osiam/osiam first.

**Comment by tkrille** [comment]
Done.

**Comment by dacrome** [comment]
Thanks!

You forgot some OSIAM "server" occurrences:
https://github.com/tkrille/osiam-addon-self-administration/blob/support-merge/docs/deployment.md
https://github.com/tkrille/osiam-addon-self-administration/blob/support-merge/docs/email-templating.md
https://github.com/tkrille/osiam-addon-self-administration/blob/support-merge/docs/user-registration.md#orgosiamhtmlformextensions

And some "wiki" occurrences:
https://github.com/tkrille/osiam-addon-self-administration/blob/support-merge/README.txt

Please delete [the first section](https://github.com/tkrille/osiam-addon-self-administration/blob/support-merge/docs/README.md), the wiki item does not exists anyway.

Please change it to "A self administration for OSIAM" (or "The self administration for OSIAM"?) in the [README.md](https://github.com/tkrille/osiam-addon-self-administration/blob/support-merge/README.md) and the [pom.xml](https://github.com/tkrille/osiam-addon-self-administration/blob/support-merge/pom.xml#L40)

**Comment by tkrille** [comment]
all done

**Comment by dacrome** [comment]
Thank you!

**Pull request merged**
