### PR TITLE
Get rid off the plugin example dependency

### PR DESCRIPTION
**Pull request by dacrome**
To test the plugin mechanism for the registration process, an
example implementation was created as dependency. This PR moves
the plugin example to the test code base and creates the jar
within the integration tests preparation.

### CODE REVIEW

**Comment by tkrille** [comment]
Commit message: Typo "resgistration", Typo: "preperation"

**Comment by dacrome** [comment]
Ups, sorry. Anything else?

**Comment by tkrille** [comment]
This is really a very unconventional way to solve the problem with the plugin example. But I cannot think of any other way neither. So, no, nothing else.

**Comment by dacrome** [comment]
Actually, I love to solve problems on an unconventional way. Sometimes ;)

**Comment by dacrome** [comment]
Updated.

**Pull request merged**
