### PR TITLE
Switch to Spring Boot fat jar

### LINKED ISSUE #120: Spring Boot: Which default port should we use?
If we migrate to Spring Boot, we need to set a default ports for the service and the admin/metrics endpoints. Any suggestions? Remember that we need to set two ports for every OSIAM component (auth-server, resource-server, self-administration, addon-administration). Maybe something like:
Service: 41001
Admin: 42001

### LINKED ISSUE #121: Run the self-administration as a standalone application
Like [already discussed](https://github.com/osiam/osiam/issues/5) in the OSIAM umbrella repo, the time is right to support standalone application with Spring Boot fat jars. But there are several steps to discuss for an easy migration and what of the Spring Boot magic we should use to make the life easier for operations and developers. I will create a few issues to discuss these steps. This issue was only created to clarify the need for the migration to Spring Boot. This issue will be closed if the migration is finally done!

### PR DESCRIPTION
**Pull request by dacrome**
* Finally migrate to Spring Boot fat jar!
* Run the self-administration with java -jar addon-self-administration.jar
* Customization of configuration
    * --spring.config.location=/path/to/config.properties
    * application.properties in the current folder
    * [other options](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files)
* Customization of the web-resources like templates
    * setting `org.osiam.external.resources.path`within the external application.properties where to find these files
    * use the same folder structure, but not need to override all files
    * first located file will be used, if no external the internal one will be used
* Using default port `50513` for the self-administration like [here discussed](https://github.com/osiam/addon-self-administration/issues/120)

Closes #120
Closes #121

### CODE REVIEW

**Comment by dacrome** [comment]
There is still much stuff to do before merging this:
* Update docs in this repo and [osiam umbella repo](https://github.com/osiam/osiam)
* Update CHANGELOG.md and the README.txt for distribution
* Needs update
    * [docker-image](https://github.com/osiam/docker-image)
    * [vagrant](https://github.com/osiam/vagrant)
    * [distribution](https://github.com/osiam/distribution)
    * [test-suites / performance-tests](https://github.com/osiam/test-suites)

Anything else to update?

**Comment by dacrome** [comment]
corresponding integration-tests https://github.com/osiam/connector4java-integration-tests/pull/230

**Comment by dacrome** [comment]
Rebased and updated.
We still need to discuss about the external configuration (#122).
Currently the external configuration will be enabled by setting the `org.osiam.external.resources.path` property. If not, the internal resources will be used, which are located in [src/main/resources](https://github.com/dacrome/addon-self-administration/tree/switch-to-spring-boot/src/main/resources).

**Comment by dacrome** [comment]
I forgot something about the resources configuration: If the external resources property is set, this is the first place to search for an resource file. If not available, the internal resource file will be used. So the installers only need to copy their changed files to the external path.

**Comment by tkrille** [comment]
I'm sorry, but this won't happen: https://github.com/osiam/osiam/issues/5#issuecomment-153096062

**Pull request closed without merging**
